### ISSUE TITLE
Timber Design Parameters

### ISSUE THREAD

**Issue by Marco-Pellegrino** [strusoft/femdesign-api#678] opened 2023-01-24 11:07 UTC
A Master Thesis would require the following parameters to be implemented

**CLT Fire Design Parameters**

- Fire Duration
- Section Exposure

**CLT Design Parameter**
 - they seems to be only 5 so it shouldn't take too much time

- [ ] #228 
- [ ] #229

**Comment by andosca** [comment] 2023-02-09 07:17
Duplicate of #691

**Closed by andosca** 2023-02-09 07:17 UTC
Labels: type:feature, nice to have, framework:grasshopper, type:improvement, type:proposal, framework:c#
