### ISSUE TITLE
Creep and shrinkage automatic calculation in SetConcreteMaterialProperties Gh component

### ISSUE THREAD

**Issue by lorinczandrea** [strusoft/femdesign-api#930] opened 2024-01-09 12:26 UTC
https://femdesign-api.discourse.group/t/creep-calculation-node/138

Note:
![image](https://github.com/strusoft/femdesign-api/assets/107181445/8759cac0-00dc-4171-b1db-657b39963adb)

![image](https://github.com/strusoft/femdesign-api/assets/107181445/e2a92d70-b234-413a-966c-fd7722ccbd45)

**Comment by lorinczandrea** [comment] 2024-01-09 12:27
@Marco-Pellegrino

**Comment by Marco-Pellegrino** [comment] 2024-01-22 08:59
duplicate of #936

**Closed by Marco-Pellegrino** 2024-01-22 08:59 UTC
Labels: framework:grasshopper, request:user, type:improvement, framework:c#
