### ISSUE TITLE
Implement construction stages

### ISSUE THREAD

**Issue by xRadne** [strusoft/femdesign-api#355] opened 2022-05-09 07:40 UTC
_Once available in fdscript. Waiting for [119444](https://strusoft.fogbugz.com/f/cases/119444/)_

### From the API we should be able to 
- [ ] Create construction stages
- [ ] Assign elements to a stage
- [ ] Assign load case to a stage
- [ ] Analysis of construction stages with ghost/tracking setting

**Comment by andosca** [comment] 2022-06-14 11:47
Duplicate of #380

**Closed by andosca** 2022-06-14 11:47 UTC
Labels: duplicate
