### ISSUE TITLE
Make it possible to run analysis in C# without so many rows of code

### ISSUE THREAD

**Issue by johannariad** [strusoft/femdesign-api#217] opened 2022-02-23 13:05 UTC
It confuses and seems a bit unneccessary

**Comment by andosca** [comment] 2022-02-24 07:40
Please specify :)

**Comment by JRiad** [comment] 2022-02-24 07:46
//Run analysis
Calculate.Analysis analysis = new Calculate.Analysis(null, null, null, null, true, false, false, false, false, false, false, false, false, false, false, false, false);
FemDesign.Calculate.FdScript fdScript = FemDesign.Calculate.FdScript.Analysis(outPathIndividual, analysis, bscPaths, "", true);
Calculate.Application app = new Calculate.Application();
app.RunFdScript(fdScript, false, true, true);


The part about creating an analysis, creating an fdscript, creating an app and then running the app should be possible to make more efficient. So that it works more like the GH component

**Comment by andosca** [comment] 2022-02-25 10:19
Duplicate of #223

**Closed by andosca** 2022-02-25 10:19 UTC
