### ISSUE TITLE
Labelled section component

### ISSUE THREAD

**Issue by andosca** [strusoft/femdesign-api#554] opened 2022-10-13 05:45 UTC
https://strusoft.freshdesk.com/a/tickets/24574

Create GH component to define, evaluate and read results of labelled sections.

- [x] Constructor
- [x] Deconsstructor
- [x] Result reader

**Comment by xRadne** [comment] 2022-10-13 06:44
C# classes already exists. 

Duplicate of #200 (closed by @Marco-Pellegrino?)

**Comment by xRadne** [comment] 2022-10-13 07:06
@andosca if it is of interest. It is quite easy to add LabelledSection to a model using C# component and a few lines of code:

![image](https://user-images.githubusercontent.com/32938476/195525794-b1d7ca41-dd80-46a4-8898-36ce0f305168.png)

**Comment by JRiad** [comment] 2022-11-02 14:51
@Marco-Pellegrino @andosca
I just helped a customer with this, labelled sections seem to be popular 😄 
Just a comment, if we add a "create" component, please also remember to add labelled sections to deconstruct component

**Comment by Marco-Pellegrino** [comment] 2022-11-02 15:25
I also had a request from two students :)
Labelled Sections is the Element of the Month!

**Comment by xRadne** [comment] 2022-11-02 15:48
Should we also add result **points** while we create labelled sections? Or are result points unnecessary if we implement labelled sections?

**Comment by JRiad** [comment] 2022-11-03 07:24
Result points are also good. My guess is that they are not as commonly used as labelled sections, but it would make sense to add them as well, because they are a similar type of object

**Closed** 2022-11-04 14:44 UTC
Labels: priority:next, framework:grasshopper, user-request

**Comment by Marco-Pellegrino** [comment] 2022-11-04 14:47
https://github.com/strusoft/femdesign-api/commit/598bb9f61cdfafa4885da8b626658ae369371ac5
