### ISSUE TITLE
Line connection constructor in Grasshopper

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#589] opened 2022-11-07 12:20 UTC
https://strusoft.freshdesk.com/a/tickets/25139

![image](https://user-images.githubusercontent.com/89396751/200308797-7c4fd9c2-1459-4ba8-9bbc-3b8edae3aa8d.png)
Needed asap for a user project

**Comment by xRadne** [comment] 2022-12-01 09:57
Should be possible using C# or C# component inside Grasshopper. If needed asap.

**Comment by xRadne** [comment] 2022-12-08 10:25
Duplicate of #451

**Comment by JRiad** [comment] 2022-12-09 13:29
Surface connections are rarely used but I think point connections could be useful in the near future (in an internal project). If you have time could you implement this also for 21.7.0?

**Closed** 2022-12-19 10:08 UTC
Labels: priority:next, framework:grasshopper, request:user
