### ISSUE TITLE
Select objects in FEM-Design to modify using the API

### ISSUE THREAD

**Issue by JRiad** [strusoft/femdesign-api#347] opened 2022-05-05 09:41 UTC
A customer had a question of whether this could be possible. Not at the moment, but would it be possible at all to implement selecting objects in the FEM-Design model and import into for example GH or C# to modify?

**Comment by Marco-Pellegrino** [comment] 2023-11-15 14:38
duplicate of #890

**Closed by Marco-Pellegrino** 2023-11-15 14:38 UTC
Labels: type:proposal, priority:unset
